name: Build (Auto)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        persist-credentials: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build dependencies
      run: |
        cd node_modules/scratch-blocks && npm run prepublish && cd ../..
        cd node_modules/@turbowarp/scratch-l10n && npm run build && cd ../..
    - name: Prepare extensions
      # Don't need to do a full fetch, that would just cause a lot of unnecessary traffic
      run: node scripts/prepare-extensions.mjs
    - name: Debug scratch-blocks
      run: |
        ls scratch-blocks || true
        ls node_modules/scratch-blocks || true
        ls node_modules/scratch-blocks/shim || true
    - name: Compile
      run: npm run webpack:compile
    - name: Package
      run: npm run electron:package:dir
